shelf = [ 
    {'id' : 1,
    'name': 'headsets',
    'unit price': 150000,
    'rating': 3,
    'stock': 40},
    {'id' : 2,
    'name': 'mouse',
    'unit price': 60000,
    'rating': 4,
    'stock': 70},
    {'id' : 3,
    'name': 'charger',
    'unit price': 150000,
    'rating': 3,
    'stock': 17},
    {'id' : 4,
    'name': 'keyboard',
    'unit price': 60000,
    'rating': 3,
    'stock': 16},
    {'id' : 5,
    'name': 'monitor',
    'unit price': 2000000,
    'rating': 5,
    'stock': 7}
    ,
    {'id' : 6,
    'name': 'webcam',
    'unit price': 450000,
    'rating': 5,
    'stock': 39}
    ]